name = "Szysz Modpack"
author = "Szysz"
version = "1.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "00f894fdb74d99b4a522aa0fd96456e1e925832512a3cdbc3e99e6db8f0ae59e"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"
