hash-format = "sha256"

[[files]]
file = "datapacks/armor-statues-datapack.pw.toml"
hash = "c9d215756d276588de476a1b5905bef6c7b0f0e138de8064aa94cdc28533bf10"
metafile = true

[[files]]
file = "datapacks/purpurpack-axolotls-ignore-passives.pw.toml"
hash = "d33074cd7e85e3d4734a68de18c5a003b6128ceb6d4f3589e65b74a38f14fa38"
metafile = true

[[files]]
file = "datapacks/purpurpacks-copper-block-beacon-base.pw.toml"
hash = "27782a13a60c59e5a46446443e8e33042acf2815b8a673eab4e3081b6caf3947"
metafile = true

[[files]]
file = "datapacks/purpurpacks-more-dyed-wool-and-carpet.pw.toml"
hash = "3e196220021037037fc65fb1f9eb8764168f295bafa6178383aa72b1a9e4e9ec"
metafile = true

[[files]]
file = "datapacks/purpurpacks-one-step-dyed-shulker-boxes.pw.toml"
hash = "69bca568cd50be4bef6615bf1fa8d2da4edfa9ee8840b3681ac99312e1a28de9"
metafile = true

[[files]]
file = "datapacks/purpurpacks-re-dye-concrete-powder.pw.toml"
hash = "863f78971e1002d202fc72d8c641e460fddcb5519d800d737057dbd2cff415dd"
metafile = true

[[files]]
file = "datapacks/purpurpacks-re-dye-concrete.pw.toml"
hash = "b39f6e2430e4d6cbd183ec2a0d2911aa30fa56029da414f712eff55988396b58"
metafile = true

[[files]]
file = "datapacks/purpurpacks-re-dye-glass.pw.toml"
hash = "ed9fbaae1da803882e83ec213885574c5e12cedfe68e9d0ea8e5a9ae5db50970"
metafile = true

[[files]]
file = "datapacks/purpurpacks-re-dye-glazed-terracotta.pw.toml"
hash = "c2c8c898b8b8af7d186e9c713d13c6a4ec11b33ee10c6b875908b021983ca1a0"
metafile = true

[[files]]
file = "datapacks/purpurpacks-re-dye-terracotta.pw.toml"
hash = "1bd442402fd113f12f045371533acac2d160b64ad16f45c756151c077a95749e"
metafile = true

[[files]]
file = "datapacks/purpurpacks-silk-touch-budding-amethyst.pw.toml"
hash = "a6510eca69d86a4fefff67c2189a1a2de5c09527a78059c8217d967844f5be8e"
metafile = true

[[files]]
file = "datapacks/purpurpacks-transparent-blocks-in-enchant-area.pw.toml"
hash = "905736efe3b643fbd1ccbd434d2892a2a3436e319bc9fb915dd52d4c9294c09c"
metafile = true

[[files]]
file = "mods/alternate-current.pw.toml"
hash = "ddc96b08f1a32a08edd9b8e34257b9a37ea9b3836ae4371e26f54c4ade4fe3f1"
metafile = true

[[files]]
file = "mods/balm.pw.toml"
hash = "f34fa12fe7701cf0776fef1a1f1e2e3c7227f53302b3d87b7ff307f0446a68d2"
metafile = true

[[files]]
file = "mods/bettercoppergolem.pw.toml"
hash = "953b6bd613d4e6acc8581c59e0265367a5c005fb29287736da21b169c070b7e7"
metafile = true

[[files]]
file = "mods/bluemap.pw.toml"
hash = "24737d4ec343e590df0fb597f52bd792557300b659b828492bfd51d63c1fe52d"
metafile = true

[[files]]
file = "mods/bmm.pw.toml"
hash = "5bbd96d22147d6a54ae474cfb3e3e49e433a02754811db4610b5895f7bc9f2f4"
metafile = true

[[files]]
file = "mods/c2me-fabric.pw.toml"
hash = "4ee1808a7fb319d469dece5752cedb05dacb9afbe48021fa664f54b8c83fdc45"
metafile = true

[[files]]
file = "mods/calcmod.pw.toml"
hash = "6ebb236b2a46dbf564aa2760a68027703e44105ab18e77ea76c0fe2323a9bafb"
metafile = true

[[files]]
file = "mods/carpet.pw.toml"
hash = "c6214a3903e034a911d984f84a98ad04fd7a0f76431d16986458ceb782b7d8c1"
metafile = true

[[files]]
file = "mods/chunk-sending-forge-fabric.pw.toml"
hash = "1edd2cfabb619660184561ab311bf5a6ad8d49d950030de1fef3cae4f9a549dd"
metafile = true

[[files]]
file = "mods/chunky.pw.toml"
hash = "64badefe03082699f587274a31d1f0793583a4d88aac8ea2226162f80783fb52"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "717d8ac591dba59be4767a179e1359747561e54ccfcac42161fd6bf54339a78b"
metafile = true

[[files]]
file = "mods/collective.pw.toml"
hash = "3d24d58b2caf4fd73d76b2d734a1d06490994d5d38177376e6f5d8d9f8fb87e0"
metafile = true

[[files]]
file = "mods/crafting-tweaks.pw.toml"
hash = "5f25fc8e02e8d0822ab8b02f730d7b657ae100f4af40b51279604e7600fbabdd"
metafile = true

[[files]]
file = "mods/craterlib.pw.toml"
hash = "d036c801bc536e98cb8e5fb4c6a4be038d5e4facae4a73850588f58559cceb48"
metafile = true

[[files]]
file = "mods/cupboard.pw.toml"
hash = "f67b2da196e96f6a086b8c60d3f1d4b18c1c54d65056c003723fa22213bb4678"
metafile = true

[[files]]
file = "mods/datapack-injector.pw.toml"
hash = "67c1fc85b89261af425055417fe6e85e4981b7d61662fe4f79d50a734e9738da"
metafile = true

[[files]]
file = "mods/dcintegration.pw.toml"
hash = "1a3c70470af98fcf70c22dfa16f64e4259458072290c4ab1e31569874e709358"
metafile = true

[[files]]
file = "mods/essential-commands.pw.toml"
hash = "1fc15d0ee6913ae274b146a8bfcb0f0992b35126583b3b9dd6811820c1466d67"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "cbda4f1881cfb9f054395a3db225df4202d1f2e7bd0ed27d803b837fcf728621"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "d7c055f277c1751122d9abc5f09015e629699e04a9383cd0c666b33436293079"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "186a261ded1911abf559dce21b22eadc1e96de7767982e58f458b82a89a924ba"
metafile = true

[[files]]
file = "mods/inventory-sorting.pw.toml"
hash = "30c3bef55b693eaef69d95827eaa0d6d4dd47f995ce2f6409a6b4077ba6f5300"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "84957275e9dc6f07f4244ce3303536e3d73b0e72eb1696ccd024168a52c29c98"
metafile = true

[[files]]
file = "mods/luckperms.pw.toml"
hash = "78eb7a4883effdbab78ff513fba684e62783bad2ef54b1aeef0fe584af490c67"
metafile = true

[[files]]
file = "mods/maintenancemode.pw.toml"
hash = "be97476a17c343a9e5c2b5ba2616ed77b134777ceb23fa40940abd42acc128c2"
metafile = true

[[files]]
file = "mods/mysql-jdbc.pw.toml"
hash = "6c82993a705738c3baad5df1728282c4da76add31e6f2e45227ddcb6313fb1f5"
metafile = true

[[files]]
file = "mods/polymer.pw.toml"
hash = "22a83a04b4df87ab4bbea18228c3cc695551610c66cc79ccc315d783d3f7848f"
metafile = true

[[files]]
file = "mods/silk.pw.toml"
hash = "493a76add332abb0dfa23004300ea2ae77a8448960f603519c1db5ab4d769413"
metafile = true

[[files]]
file = "mods/simple-voice-chat.pw.toml"
hash = "cdde1ed66709cde0656be902a1109532f255fd1526991acebe91116a4ab399df"
metafile = true

[[files]]
file = "mods/skinrestorer.pw.toml"
hash = "f9ad248cda9947bf9336af6cb6537f4533ca79325128fbb22999fb19eaea22f5"
metafile = true

[[files]]
file = "mods/spark.pw.toml"
hash = "2520b331c2b0eb582b448c4ebf1a73d66d42184acc2d74912baef4140e05ee9b"
metafile = true

[[files]]
file = "mods/tree-harvester.pw.toml"
hash = "7b976155d02000a064de326c3918686bc8be05125a16570659c5f5c9feab768b"
metafile = true

[[files]]
file = "mods/universal-graves.pw.toml"
hash = "ed9329edc09aae7041d14e6f68563b9235a10163e4fc9e4e31d5a2d81883845e"
metafile = true

[[files]]
file = "mods/veinminer.pw.toml"
hash = "5cb9a93032a75644cdf442b05a29e0616c76df503ee6b3dd3ab367ad1a04ff60"
metafile = true

[[files]]
file = "mods/view-distance-fix.pw.toml"
hash = "af324ff6ff0e13779b645d543d77c725f71628feb2a23de2e5e053bfa94532f9"
metafile = true

[[files]]
file = "mods/xaeros-world-map.pw.toml"
hash = "53c8bc02c9b10610c43fc29127039036217e33a95ab2ea2d6ac291987266ef89"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "e71ac6769675de1d2338a13e116f2aefcc8965ab0bc18b75a53572531c1447dd"
metafile = true
