hash-format = "sha256"

[[files]]
file = "datapacks/anti enderman grief v1.1.15 (MC 1.21-1.21.11).zip"
hash = "5cb612407cb72ac8e9629287fdc903b3b9df6cef379e2d2e1875edbd7dddc1b1"

[[files]]
file = "datapacks/armor-statues-datapack.pw.toml"
hash = "c9d215756d276588de476a1b5905bef6c7b0f0e138de8064aa94cdc28533bf10"
metafile = true

[[files]]
file = "datapacks/coordinates hud v1.2.16 (MC 1.21-1.21.11).zip"
hash = "f40582e026e982aa1aa402f4f4a23fde41653fac879867a2fb6baa555b1d18ea"

[[files]]
file = "datapacks/double shulker shells v1.3.15 (MC 1.21-1.21.11).zip"
hash = "4eb19b2261634f41e6585564d5e01f178efa0d656e1d451d4f77252329043913"

[[files]]
file = "datapacks/mini blocks v1.1.5 (MC 1.21-1.21.11).zip"
hash = "d710a44f67f2ab175384bcb7a581150f03e258f29199d1c88cc526cd2df50215"

[[files]]
file = "datapacks/more mob heads v2.18.0 (MC 1.21-1.21.11).zip"
hash = "fb5508605f6712f9999a134664670273241334ddab97fce899789cdcdfbd9f95"

[[files]]
file = "datapacks/multiplayer sleep v2.6.15 (MC 1.21-1.21.11).zip"
hash = "f772d4b90358cc0266f73c6a8cc9d9dbd849d1c50bff085f644bdb76b75c4b28"

[[files]]
file = "datapacks/nether portal coords v1.1.15 (MC 1.21-1.21.11).zip"
hash = "2277092a3b9c27d54db7bc7a0d0e2d7325ff853c12e009053f2ce955f683f29a"

[[files]]
file = "datapacks/player head drops v1.1.15 (MC 1.21-1.21.11).zip"
hash = "3513d89915854e09f4f112f230f1eed91b53a80fe22a02f320277654c15e04f3"

[[files]]
file = "datapacks/silence mobs v1.2.9 (MC 1.21-1.21.11).zip"
hash = "f10a5d01b4ab1e660c963acc3e51b3615db170fc8dfe89e835fe4f331e8760b5"

[[files]]
file = "datapacks/spawning spheres v1.1.15 (MC 1.21-1.21.11).zip"
hash = "2e99c81390ff3604b98a213e6c5d4eff59c5d70fad14bc92c0cbe3e4dd6be0a2"

[[files]]
file = "datapacks/track raw statistics v1.7.11 (MC 1.21-1.21.11).zip"
hash = "3ba118c7182307739df6ae69779df58efb3fbf66bbb07947b251304441f2b8de"

[[files]]
file = "datapacks/unlock all recipes v2.0.16 (MC 1.21-1.21.11).zip"
hash = "de8ae409b1b0fa48512449bc72ee06388fbbb30098307cd54481e5dd3dd9e96a"

[[files]]
file = "datapacks/villager workstation highlights v1.1.15 (MC 1.21-1.21.11).zip"
hash = "8517a048e53454673845e2f35bc04a1f60249b5b21af5976a2fb8aa89f281269"

[[files]]
file = "datapacks/wandering trader announcements v1.0.8 (MC 1.21-1.21.11).zip"
hash = "c3e28b635024d4eb5e021235d52d2ad87620c700de0cdda0de0c5c759f61637a"

[[files]]
file = "datapacks/wandering trades v1.7.14 (MC 1.21-1.21.11).zip"
hash = "f9162390d08d058034f536bb5f5e8d87237d44d8a715058778ead6edd675d18e"

[[files]]
file = "mods/alternate-current.pw.toml"
hash = "fc8ffe66dc0c7eb55cf2ce38d1ae4bf1c4cdfbfdcda2636b1cd140c851e03cc5"
metafile = true

[[files]]
file = "mods/balm.pw.toml"
hash = "5d0603e338ddb39ddbac6c1732639c6b55c968e6a9dc9aab981dcae5ad3c34cf"
metafile = true

[[files]]
file = "mods/bettercoppergolem.pw.toml"
hash = "9fc96f4a90b374adef380353c6c9947e540fe85bfa7551a8ffbb7dcc33d3a75e"
metafile = true

[[files]]
file = "mods/bluemap.pw.toml"
hash = "853ba2ec022456ae2f357268a27c7cb1018b0c57e0c1e9071330f81e035f59f9"
metafile = true

[[files]]
file = "mods/bmm.pw.toml"
hash = "6f2341c3aa7128726dc3c6f179cbfa69ba7e1e22f5a784fb9e3cea7da7ad1863"
metafile = true

[[files]]
file = "mods/c2me-fabric.pw.toml"
hash = "ff260b35492778bdce59ffa064a59c6a9953ffd409eb40782af14b78a29a2cb8"
metafile = true

[[files]]
file = "mods/calcmod.pw.toml"
hash = "6ebb236b2a46dbf564aa2760a68027703e44105ab18e77ea76c0fe2323a9bafb"
metafile = true

[[files]]
file = "mods/carpet.pw.toml"
hash = "ed55fdea501426bbabdbe8f3ed4440158a17c435b978d5d38b4a926e53cdfd6f"
metafile = true

[[files]]
file = "mods/chunk-sending-forge-fabric.pw.toml"
hash = "1edd2cfabb619660184561ab311bf5a6ad8d49d950030de1fef3cae4f9a549dd"
metafile = true

[[files]]
file = "mods/chunky.pw.toml"
hash = "eaa52d6ff1bcb539956d50626085d9185eca346fabcf6b3c176c53192b9958ec"
metafile = true

[[files]]
file = "mods/cloth-config.pw.toml"
hash = "a06ef129798265e0d7249426fb0ed5c506725b0460dc3dfdb975b8978480895e"
metafile = true

[[files]]
file = "mods/collective.pw.toml"
hash = "c2a61b492dd0d7a156e15b7572adb40552b94c09658cc3c6d7faf99288d094c7"
metafile = true

[[files]]
file = "mods/crafting-tweaks.pw.toml"
hash = "1c0119cea1e398bc5192c42ba23c93857335e791c4ee4644fd98689a1863d17f"
metafile = true

[[files]]
file = "mods/craterlib.pw.toml"
hash = "d036c801bc536e98cb8e5fb4c6a4be038d5e4facae4a73850588f58559cceb48"
metafile = true

[[files]]
file = "mods/cupboard.pw.toml"
hash = "ac13f85b3ba6ca40c3e760041c105ecfce89638700552dc2fe7df97698680534"
metafile = true

[[files]]
file = "mods/datapack-injector.pw.toml"
hash = "669858bccb4357cf18fd7e6b479cf68589775cdef085731da0ee92d6414fa087"
metafile = true

[[files]]
file = "mods/dcintegration.pw.toml"
hash = "1a3c70470af98fcf70c22dfa16f64e4259458072290c4ab1e31569874e709358"
metafile = true

[[files]]
file = "mods/essential-commands.pw.toml"
hash = "01b068e883e786511bfc9b2cba0ef3c7af33989104f693515f6de4c6a6c551bd"
metafile = true

[[files]]
file = "mods/fabric-api.pw.toml"
hash = "7adc0d54f139075d8f90dae18ca476753cc3145a70e09c9327736024adfe9b30"
metafile = true

[[files]]
file = "mods/fabric-language-kotlin.pw.toml"
hash = "61afd7af5c645ffd966b2bd86be944eacd1e48a8044e8f67082225d4d9989f0c"
metafile = true

[[files]]
file = "mods/ferrite-core.pw.toml"
hash = "76a12a836d4c7f0f943a1e391dd2d7b5c4673caa497fff16593d49449376b117"
metafile = true

[[files]]
file = "mods/inventory-sorting.pw.toml"
hash = "1f84728bef097ce5e27cd8478dd385935746ad8f171d701f0f17dfc6be8b5a09"
metafile = true

[[files]]
file = "mods/lithium.pw.toml"
hash = "0e87ab10adb3db84b1d6d2ce8bdd7158878b56c965055056b10ad6cde2634568"
metafile = true

[[files]]
file = "mods/luckperms.pw.toml"
hash = "0fcb21a2580ad82270c404aa36e042926a7f35b0151f785bd6c6afce23e6edc4"
metafile = true

[[files]]
file = "mods/maintenancemode.pw.toml"
hash = "be97476a17c343a9e5c2b5ba2616ed77b134777ceb23fa40940abd42acc128c2"
metafile = true

[[files]]
file = "mods/malilib.pw.toml"
hash = "c8da9df94366869dacc80807029f14edb4c583420b7b2d5193d6da06e85150ea"
metafile = true

[[files]]
file = "mods/minihud.pw.toml"
hash = "6d26fbac2dca7845d5de9e5fbbe3dbcb7541ccb952e4f5f14a92e618d5448965"
metafile = true

[[files]]
file = "mods/mysql-jdbc.pw.toml"
hash = "6c82993a705738c3baad5df1728282c4da76add31e6f2e45227ddcb6313fb1f5"
metafile = true

[[files]]
file = "mods/polymer.pw.toml"
hash = "b39ee5a28d5548d591e8f396d2407893affcc71470d7c058d3287039a960e55d"
metafile = true

[[files]]
file = "mods/purpurpack-axolotls-ignore-passives.pw.toml"
hash = "0f8e63c2bf627817786455e56cc05ffa9fda4c5e7e4cc2bd794b01801810a2ad"
metafile = true

[[files]]
file = "mods/purpurpacks-copper-block-beacon-base.pw.toml"
hash = "373b120bb77c2f43136144ee1ae2f49b5711700be26f8621a972f33c37e9ecbd"
metafile = true

[[files]]
file = "mods/purpurpacks-more-dyed-wool-and-carpet.pw.toml"
hash = "68907da5711e4ed0419cdc02bf2077cbf8762fb2a0f05ca5d87bf431eaeed3c4"
metafile = true

[[files]]
file = "mods/purpurpacks-one-step-dyed-shulker-boxes.pw.toml"
hash = "3e3fce1d772288e0fcc1184524a2d627fed467c781d595b3192c1c800d131c2f"
metafile = true

[[files]]
file = "mods/purpurpacks-re-dye-concrete-powder.pw.toml"
hash = "a3ade82e36f653809143db9fce2ddb8f88ee20e8514c60b9140246d870efc41c"
metafile = true

[[files]]
file = "mods/purpurpacks-re-dye-concrete.pw.toml"
hash = "546a8bdbd8fd8b12ca66b7ce67517141152eee389360412eee57f193a321500e"
metafile = true

[[files]]
file = "mods/purpurpacks-re-dye-glass.pw.toml"
hash = "92fcd5b2b9470cd3b42a8c2bee4ae92a1255f5a4c27fbcdbb451ca81886e6287"
metafile = true

[[files]]
file = "mods/purpurpacks-re-dye-glazed-terracotta.pw.toml"
hash = "d51a9465e821ab6c67225bc63ab78f82cf43d15f70d3772b45428df860b767cb"
metafile = true

[[files]]
file = "mods/purpurpacks-re-dye-terracotta.pw.toml"
hash = "2ba0bc705c2c42bce0cb96832d279c878686b4eaceeb302b76cb02f642e6ff94"
metafile = true

[[files]]
file = "mods/purpurpacks-silk-touch-budding-amethyst.pw.toml"
hash = "f30d6cba9c40ff61cf2f7409fdfe6b35e5365e21e0a98c70e1f071fc4a8ce9ab"
metafile = true

[[files]]
file = "mods/purpurpacks-transparent-blocks-in-enchant-area.pw.toml"
hash = "95e02a0a1cdaf9dbcb8253a5df3c44c66926647d3666c4987237c1bbc4ec436c"
metafile = true

[[files]]
file = "mods/silk.pw.toml"
hash = "a4c742db2f87bd02aa5dfd47faab025d985a9e21e69c72dd923a643a7a908513"
metafile = true

[[files]]
file = "mods/simple-voice-chat.pw.toml"
hash = "0cbc900ae05bdd88801539eeee6b95dde99426f1d5c2c7c8c194e5f78bbd6e52"
metafile = true

[[files]]
file = "mods/skinrestorer.pw.toml"
hash = "779286fb8a1f7325f6ee888313506d65acc0504a6b9cfe0ed1075398048413d5"
metafile = true

[[files]]
file = "mods/spark.pw.toml"
hash = "c073f13897a838e3c409e46b8a1d8cb510d6a6584dd815aeadaf4886f1779513"
metafile = true

[[files]]
file = "mods/tree-harvester.pw.toml"
hash = "5e87caea13a44193abf997de56cf3cab2eb9feb1d8be35e0203f06df3552b9c5"
metafile = true

[[files]]
file = "mods/universal-graves.pw.toml"
hash = "c1166e4664aa67501d4daafac5e69cb29094dd46942d35e64b4d5d8a0a54decd"
metafile = true

[[files]]
file = "mods/veinminer.pw.toml"
hash = "fc7bfaa3cc133f968b1a4ee6f0635c2980fb277870aec45e9d68ff313b0d1d9d"
metafile = true

[[files]]
file = "mods/view-distance-fix.pw.toml"
hash = "54bc812ffd22a9cd2ab6f04aeff01deacf242cf83f68e71ac36ecb2e214b3fd0"
metafile = true

[[files]]
file = "mods/xaeros-world-map.pw.toml"
hash = "6d8406aec218c54091d409f50fe82531f8015cbd84e10bd360180b364460eb6b"
metafile = true

[[files]]
file = "mods/yacl.pw.toml"
hash = "6b2e6c4faa6fa928c5c5c582752b80401e418d4f897839b7d0338acc08e94803"
metafile = true
