name = "Szysz Server Pack"
author = "Szysz"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2faa670aeab926abf240d88c50cf671eb5fdad204b112edea48fe524c38443fa"

[versions]
fabric = "0.17.2"
minecraft = "1.21.8"

[options]
acceptable-game-versions = ["1.21.7"]
datapack-folder = "datapacks"
