name = "Szysz Server Pack"
author = "Szysz"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3a13bbe4f1e015f6b82e4530d373c076649a8472163e98ff0ccd735c66cff04e"

[versions]
fabric = "0.18.1"
minecraft = "1.21.10"

[options]
acceptable-game-versions = ["1.21.9"]
datapack-folder = "datapacks"
