name = "Szysz Server Pack"
author = "Szysz"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "312893b2c86cca1a7f3badb718fa6f0bc947d8272852cbbf6710bfe88b936fc0"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"

[options]
acceptable-game-versions = ["1.21.9"]
datapack-folder = "datapacks"
