name = "Szysz Server Pack"
author = "Szysz"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "73cfcc4364df27fdfea292a172ee4cd6aec899c5e8972636aca7fa482ad0833e"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"

[options]
acceptable-game-versions = ["1.21.9"]
datapack-folder = "datapacks"
