name = "Szysz Server Pack"
author = "Szysz"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "01a7362d81a2502f01fd7b7891e6c65694601b9ac36945741a2b6dbb9a9b7404"

[versions]
fabric = "0.17.3"
minecraft = "1.21.10"

[options]
acceptable-game-versions = ["1.21.9"]
datapack-folder = "datapacks"
